### ISSUE TITLE
Build a download page for photos with copyright information and terms of use

### ISSUE THREAD

**Issue by hbharker** [BrentHarker/newsnow#35]
See example from LDS.org:
http://www.mormonnewsroom.org/multimedia-download/article/women-auxiliary-leaders-meet-with-european-members

**Comment by sgwall** [comment]
View and Panel Page created to display information
http://typo.byu.edu/image-gallery?nid=##

at the moment the node ID fishes for information, when the page is created we can add a link to the news story/article and then make sure that we identify it's ID and it will jump to the displayable panel page showing their results.
