### ISSUE TITLE
Photo cropping and placement

### ISSUE THREAD

**Issue by hbharker** [BrentHarker/newsnow#63]
Editors want to crop photos in the tool, give them a variety of sizes, and place them where they want them. There are 11 modules that might work. Check out Imagefield Crop and Manual Crop. https://www.drupal.org/node/1179172

**Comment by sgwall** [comment]
I installed Imagefield Crop into the test site.  It is a field type that must be added in the content-type,  Settings are configurable, but it automatically gives crop ability as soon as image has been uploaded.
